# Clock Constraints
set_property PACKAGE_PIN E3 [get_ports sys_clock]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clock]

# DIP Switches
set_property PACKAGE_PIN F22 [get_ports {dip_switches_4bits_tri_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dip_switches_4bits_tri_i[0]}]
set_property PACKAGE_PIN F21 [get_ports {dip_switches_4bits_tri_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dip_switches_4bits_tri_i[1]}]
set_property PACKAGE_PIN E22 [get_ports {dip_switches_4bits_tri_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dip_switches_4bits_tri_i[2]}]
set_property PACKAGE_PIN E21 [get_ports {dip_switches_4bits_tri_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dip_switches_4bits_tri_i[3]}]

# Ethernet PHY
set_property PACKAGE_PIN G18 [get_ports eth_mdio]
set_property IOSTANDARD LVCMOS33 [get_ports eth_mdio]
set_property PACKAGE_PIN G19 [get_ports eth_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports eth_mdc]
set_property PACKAGE_PIN H16 [get_ports eth_txd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports eth_txd[0]]
set_property PACKAGE_PIN H17 [get_ports eth_txd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports eth_txd[1]]
set_property PACKAGE_PIN J17 [get_ports eth_txd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports eth_txd[2]]
set_property PACKAGE_PIN J18 [get_ports eth_txd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports eth_txd[3]]
set_property PACKAGE_PIN K16 [get_ports eth_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports eth_tx_en]
set_property PACKAGE_PIN H14 [get_ports eth_rxd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports eth_rxd[0]]
set_property PACKAGE_PIN H15 [get_ports eth_rxd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports eth_rxd[1]]
set_property PACKAGE_PIN J15 [get_ports eth_rxd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports eth_rxd[2]]
set_property PACKAGE_PIN J16 [get_ports eth_rxd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports eth_rxd[3]]
set_property PACKAGE_PIN G15 [get_ports eth_rx_dv]
set_property IOSTANDARD LVCMOS33 [get_ports eth_rx_dv]
set_property PACKAGE_PIN G14 [get_ports eth_rx_er]
set_property IOSTANDARD LVCMOS33 [get_ports eth_rx_er]
set_property PACKAGE_PIN G16 [get_ports eth_crs]
set_property IOSTANDARD LVCMOS33 [get_ports eth_crs]
set_property PACKAGE_PIN G17 [get_ports eth_col]
set_property IOSTANDARD LVCMOS33 [get_ports eth_col]
set_property PACKAGE_PIN H13 [get_ports eth_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports eth_tx_clk]
set_property PACKAGE_PIN H12 [get_ports eth_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports eth_rx_clk]
set_property PACKAGE_PIN F16 [get_ports eth_rstn]
set_property IOSTANDARD LVCMOS33 [get_ports eth_rstn]

# I2C
set_property PACKAGE_PIN C17 [get_ports i2c_sda]
set_property IOSTANDARD LVCMOS33 [get_ports i2c_sda]
set_property PACKAGE_PIN C18 [get_ports i2c_scl]
set_property IOSTANDARD LVCMOS33 [get_ports i2c_scl]

# I2C Pullups
set_property PACKAGE_PIN C16 [get_ports i2c_pullup_0]
set_property IOSTANDARD LVCMOS33 [get_ports i2c_pullup_0]
set_property PACKAGE_PIN D15 [get_ports i2c_pullup_1]
set_property IOSTANDARD LVCMOS33 [get_ports i2c_pullup_1]

# LEDs
set_property PACKAGE_PIN H5 [get_ports {led_4bits_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_4bits_tri_o[0]}]
set_property PACKAGE_PIN J5 [get_ports {led_4bits_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_4bits_tri_o[1]}]
set_property PACKAGE_PIN T9 [get_ports {led_4bits_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_4bits_tri_o[2]}]
set_property PACKAGE_PIN T10 [get_ports {led_4bits_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_4bits_tri_o[3]}]

# Push Buttons
set_property PACKAGE_PIN D9 [get_ports {push_buttons_4bits_tri_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {push_buttons_4bits_tri_i[0]}]
set_property PACKAGE_PIN C9 [get_ports {push_buttons_4bits_tri_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {push_buttons_4bits_tri_i[1]}]
set_property PACKAGE_PIN B9 [get_ports {push_buttons_4bits_tri_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {push_buttons_4bits_tri_i[2]}]
set_property PACKAGE_PIN B8 [get_ports {push_buttons_4bits_tri_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {push_buttons_4bits_tri_i[3]}]

# QSPI Flash
set_property PACKAGE_PIN C4 [get_ports qspi_db0]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_db0]
set_property PACKAGE_PIN D4 [get_ports qspi_db1]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_db1]
set_property PACKAGE_PIN D5 [get_ports qspi_db2]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_db2]
set_property PACKAGE_PIN D6 [get_ports qspi_db3]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_db3]
set_property PACKAGE_PIN E5 [get_ports qspi_csn]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_csn]
set_property PACKAGE_PIN F6 [get_ports qspi_sclk]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_sclk]

# UART
set_property PACKAGE_PIN C10 [get_ports usb_uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports usb_uart_rxd]
set_property PACKAGE_PIN D10 [get_ports usb_uart_txd]
set_property IOSTANDARD LVCMOS33 [get_ports usb_uart_txd]
set_property PACKAGE_PIN E16 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

# RGB LEDs
set_property PACKAGE_PIN H6 [get_ports {rgb_led_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_led_tri_o[0]}]
set_property PACKAGE_PIN J6 [get_ports {rgb_led_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_led_tri_o[1]}]
set_property PACKAGE_PIN K6 [get_ports {rgb_led_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_led_tri_o[2]}]
